language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  ## courtesy of http://conda.pydata.org/docs/travis.html
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda
  - conda info -a
install:
  - conda config --add channels conda-forge
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION obspy pycurl flake8 pytest pytest-cov webtest
  - source activate test-environment
  - pip install authlib flask flask-login flask-migrate flask-session flask-sqlalchemy psycopg2-binary
script:
  - flake8 --config=.flake8 bin/ geomagio/ test/
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
