# sudo: false indicates travis should use container infrastructure
sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
  - pipenv shell
script:
  - flake8 --config=.flake8 bin/ geomagio/ test/
  - nosetests -v .
after_success:
  - nosetests --with-coverage --cover-package=geomagio --cover-xml
  - bash <(curl -s https://codecov.io/bash)
